### ISSUE TITLE
bootloader not updated!

### ISSUE THREAD

**Issue by DigitalYemeni** [hazuki0x0/rpi-eeprom-ubuntu#1]
Hi there,

First of all, i would like to thank you for your work in getting this ported to ubuntu.

After i updated the RPi 4 8G firmware but the bootloader seems not updated. Below are my terminal commands iputs/outputs:

root@ubuntu:/usr/local/bin# sudo rpi-eeprom update
Download bootloader: https://raw.githubusercontent.com/raspberrypi/rpi-eeprom/master/firmware/critical/pieeprom-2020-09-03.bin
Download vl805 firmware: https://raw.githubusercontent.com/raspberrypi/rpi-eeprom/master/firmware/critical/vl805-000138a1.bin
Download recovery: https://raw.githubusercontent.com/raspberrypi/rpi-eeprom/master/firmware/critical/recovery.bin
Bootloader update required
Current version : 2020-03-19
Latest version  : 2020-09-03

VL805 update required
Current version : 000137ad
Latest version  : 000138a1

root@ubuntu:/usr/local/bin# sudo rpi-eeprom upgrade
Installing filmware updates...
Update bootloader    : 1584628045 -> 1599135103
Update VL805 firmware: 000137ad -> 000138a1
EEPROM updates pending. Please reboot to apply the update.
root@ubuntu:/usr/local/bin# reboot

root@ubuntu:~# sudo rpi-eeprom update
Firmwares are up to date.

root@ubuntu:~# poweroff

I removed the SD card and put the prebuilt boot USB but the RPi complained that SD is not present, so i reput the SD and booted to check the bootloader as follows:

root@ubuntu:~# vcgencmd bootloader_version                                                                                                                              
Sep  3 2020 13:11:43
version c305221a6d7e532693cc7ff57fddfc8649def167 (release)
timestamp 1599135103
root@ubuntu:~# vcgencmd bootloader_config
[all]
BOOT_UART=0
WAKE_ON_GPIO=1
POWER_OFF_ON_HALT=0
DHCP_TIMEOUT=45000
DHCP_REQ_TIMEOUT=4000
TFTP_FILE_TIMEOUT=30000
ENABLE_SELF_UPDATE=1
DISABLE_HDMI=0
BOOT_ORDER=0x1

root@ubuntu:~#

obviously the bootloader is not updated with the boot order device and missing the BOOT_ORDER=0xf41

How to fix this manually?

Thank you once again!

**Comment by hazuki0x0** [comment]
Sorry for not replying sooner.
I updated the script. You can reset the bootloader_config as follows:
`sudo rpi-eeprom upgrade --default_config`
